#!/usr/bin/env ruby -I.

require "magic_xml"
require 'trollop'

class Deck
  attr_accessor :name, :comment
  def initialize
    @main = Hash.new(0)
    @side = Hash.new(0)
    @in_sideboard = false
    @name = ""
    @comment = ""
  end

  def add_card!(name, number, sideboard=@in_sideboard)
    # Common differences between cards.xml
    # and what people type in their decklists online
    name = name.gsub("’", "'")
    if sideboard
      @side[name] += number
    else
      @main[name] += number
    end
  end

  def parse_line!(line)
    line = line.strip
    case line
    when /\ASB:\s*(\d+)\s*(.*)\z/
      add_card! $2, $1.to_i, true
    when /\A(\d+)\s*(.*)\z/
      add_card! $2, $1.to_i
    when /\ASideboard:?/i
      @in_sideboard = true
    when ""
    else
      # possibly weird stuff, ignore anyway
    end
  end

  def parse!(input)
    input.each do |line|
      parse_line! line.chomp
    end
  end

  def each_main_card(&blk)
    @main.to_a.sort.each(&blk)
  end

  def each_side_card(&blk)
    @side.to_a.sort.each(&blk)
  end

  def zone_to_xml(zone, name)
    xml(:zone, name: name) do
      zone.to_a.sort.each do |name, count|
        card! number: count, price: 0, name: name
      end
    end
  end

  def to_cod
    out = xml(:cockatrice_deck)
    out << (deckname = xml(:deckname))
    out << (comments = xml(:comments))
    out << zone_to_xml(@main, :main)
    out << zone_to_xml(@side, :side)
    out.add_pretty_printing!
    # Don't prettyprint within these
    deckname << @name
    comments << @comment
    out
  end
end

opts = Trollop::options do
  opt :name, "Deck name", type: :string, default: "Unknown"
  opt :comment, "Comment", type: :string, defaul: ""
  opt :input, "input (default STDIN)", type: :string
  opt :output, "output (default STDOUT)", type: :string
end

deck = Deck.new
deck.name = opts[:name]
deck.comment = opts[:comment]
deck.parse!(opts[:input] ? File.readlines(opts[:input]) : STDIN.readlines)
if opts[:output]
  File.open(opts[:output], 'w') do |fh|
    fh.puts deck.to_cod
  end
else
  puts deck.to_cod
end
