#!/usr/bin/env ruby

require "trollop"
require_relative "cockatrice"
require "open-uri"
require "nokogiri"

class DeckImporter
  attr_reader :url

  def initialize(url)
    @url = url
  end

  def host
    URI.parse(url).host
  end

  def doc
    @doc ||= Nokogiri::HTML(open(url).read)
  end

  def import_wizardscom!
    doc.css(".deck").each do |node|
      title = node.css('heading').text.strip
      link = URI.parse(@url) + node.css('.dekoptions a')[0][:href]
      parser = TextDeckParser.new
      parser.empty_line_starts_sideboard = true
      deck = parser.parse! open(link)
      deck.name = title
      deck.comment = url
      file_name = title.gsub("/", "") + ".cod"
      deck.save_as!(file_name)
    end
  end

  def import_scg!
    deck = Deck.new
    doc.css(".deck_card_wrapper li").each do |cards|
      in_sideboard = !cards.ancestors(".deck_sideboard").empty?
      raise "Parse error: `#{cards}'" unless cards.text =~ /\A(\d+)\s+(.*)/
      deck.add_card! $2, $1.to_i, in_sideboard
    end
    title = doc.css(".deck_title").text
    deck.name = title
    deck.comment = @url
    file_name = title.gsub("/", "") + ".cod"
    deck.save_as!(file_name)
  end

  def import!
    if host == "www.wizards.com"
      import_wizardscom!
    elsif host == "sales.starcitygames.com"
      import_scg!
    else
      raise "Don't know how to import from #{host}"
    end
  end
end

ARGV.each do |url|
  importer = DeckImporter.new(url).import!
end
